# KRM-style metadata for the Terraform Google IAM module.
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-iam
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    # Required. Machine-readable name of the blueprint.
    name: terraform-google-iam
    source:
      # Required. Details about the source repository.
      sourceType: git
      git:
        repo: https://github.com/GoogleCloudPlatform/terraform-google-iam.git
        # The directory within the repo containing the blueprint.
        dir: /
    # The current release version of the blueprint.
    version: 1.0.0
    # The tool used to actuate the blueprint.
    actuationTool:
      # Required. Type of actuation tool.
      type: Terraform
      # Required. Version of the tool.
      version: ">= 1.3.0"
    # Required. Human-readable title of the blueprint.
    title: IAM Module
    # Required. Descriptions of the blueprint.
    description:
      # Required. A short description of the blueprint.
      tagline: A comprehensive module for managing Google Cloud IAM policies.
      # Required. A long description of the blueprint.
      detailed: This module manages authoritative and non-authoritative IAM policies for various Google Cloud resources. It allows specifying both `iam_binding` and `iam_member` policies for projects, folders, organizations, storage buckets, Pub/Sub topics, and service accounts.
    # Links to official documentation.
    documentation:
    - title: "Terraform Registry"
      url: "https://registry.terraform.io/modules/terraform-google-modules/iam/google"
    # List of examples for using the blueprint.
    examples:
    - name: project_iam
      title: Project IAM Example
      location:
        sourceType: git
        git:
          repo: https://github.com/terraform-google-modules/terraform-google-iam.git
          dir: examples/project_iam
          ref: main
    - name: organization_iam
      title: Organization IAM Example
      location:
        sourceType: git
        git:
          repo: https://github.com/terraform-google-modules/terraform-google-iam.git
          dir: examples/organization_iam
          ref: main
    # Labels for organizing and searching for the blueprint.
    labels:
      "service": "iam"
      "platform": "gcp"

  # Defines the inputs and outputs of the blueprint.
  customization:
    # A list of input variables for the blueprint.
    variables:
    - name: folder_bindings
      description: A map of authoritative folder-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: folder_members
      description: A map of non-authoritative folder-level IAM members to create.
      type: object
      required: false
      default: {}
    - name: organization_bindings
      description: A map of authoritative organization-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: organization_members
      description: A map of non-authoritative organization-level IAM members to create.
      type: object
      required: false
      default: {}
    - name: project_bindings
      description: A map of authoritative project-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: project_members
      description: A map of non-authoritative project-level IAM members to create.
      type: object
      required: false
      default: {}
    - name: pubsub_topic_bindings
      description: A map of authoritative Pub/Sub topic-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: pubsub_topic_members
      description: A map of non-authoritative Pub/Sub topic-level IAM members to create.
      type: object
      required: false
      default: {}
    - name: service_account_bindings
      description: A map of authoritative service account-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: service_account_members
      description: A map of non-authoritative service account-level IAM members to create.
      type: object
      required: false
      default: {}
    - name: storage_bucket_bindings
      description: A map of authoritative storage bucket-level IAM bindings to create.
      type: object
      required: false
      default: {}
    - name: storage_bucket_members
      description: A map of non-authoritative storage bucket-level IAM members to create.
      type: object
      required: false
      default: {}

    # Groups of related variables.
    variableGroups:
    - name: project_iam
      title: Project IAM
      description: Configure IAM policies at the project level.
      variables:
      - project_bindings
      - project_members
    - name: folder_iam
      title: Folder IAM
      description: Configure IAM policies at the folder level.
      variables:
      - folder_bindings
      - folder_members
    - name: organization_iam
      title: Organization IAM
      description: Configure IAM policies at the organization level.
      variables:
      - organization_bindings
      - organization_members
    - name: storage_bucket_iam
      title: Storage Bucket IAM
      description: Configure IAM policies for Cloud Storage buckets.
      variables:
      - storage_bucket_bindings
      - storage_bucket_members
    - name: pubsub_topic_iam
      title: Pub/Sub Topic IAM
      description: Configure IAM policies for Pub/Sub topics.
      variables:
      - pubsub_topic_bindings
      - pubsub_topic_members
    - name: service_account_iam
      title: Service Account IAM
      description: Configure IAM policies for service accounts.
      variables:
      - service_account_bindings
      - service_account_members

    # A list of the outputs of the blueprint.
    outputs:
    - name: folder_bindings
      description: A map of the created folder-level IAM bindings.
    - name: folder_members
      description: A map of the created folder-level IAM members.
    - name: organization_bindings
      description: A map of the created organization-level IAM bindings.
    - name: organization_members
      description: A map of the created organization-level IAM members.
    - name: project_bindings
      description: A map of the created project-level IAM bindings.
    - name: project_members
      description: A map of the created project-level IAM members.
    - name: pubsub_topic_bindings
      description: A map of the created Pub/Sub topic-level IAM bindings.
    - name: pubsub_topic_members
      description: A map of the created Pub/Sub topic-level IAM members.
    - name: service_account_bindings
      description: A map of the created service account-level IAM bindings.
    - name: service_account_members
      description: A map of the created service account-level IAM members.
    - name: storage_bucket_bindings
      description: A map of the created storage bucket-level IAM bindings.
    - name: storage_bucket_members
      description: A map of the created storage bucket-level IAM members.

  # Defines the requirements for deploying the blueprint.
  requirements:
    # GCP IAM roles required for the service account to deploy the blueprint.
    roles:
    - level: Project
      roles:
      - roles/resourcemanager.projectIamAdmin
      - roles/iam.serviceAccountAdmin
      - roles/pubsub.admin
      - roles/storage.admin
    - level: Folder
      roles:
      - roles/resourcemanager.folderIamAdmin
    - level: Organization
      roles:
      - roles/resourcemanager.organizationAdmin
    # GCP APIs that must be enabled to deploy the blueprint.
    services:
    - cloudresourcemanager.googleapis.com
    - iam.googleapis.com
    - pubsub.googleapis.com
    - storage.googleapis.com
